### ISSUE TITLE
Can't set text

### ISSUE THREAD

**Issue by Petrarca181** [zleao/zoft.MauiExtensions.AutoCompleteEntry#3] opened 2023-06-16 11:59 UTC
Hi, this is my entry, it's inside DataTemplate of CollectionView

```
<zoft:AutoCompleteEntry
 Grid.Column="0"
 Margin="5"
 DisplayMemberPath="nomeCognome"
 FontAttributes="Bold"
 FontSize="{markups:OnScreenSize
 Medium='10',
 Large='15',
 ExtraLarge='25'}"
 ItemsSource="{Binding Path=AsbItemsource, Mode=OneWay}"
 Text="{Binding Path=Name, Mode=TwoWay}"
 TextChangedCommand="{Binding Path=TextChangedCommand, Mode=OneWay}"
 TextMemberPath="nomeCognome"
/>
```

It works fine when I insert data.  But if I attach  the new ItemSource already filled with information  AutoCompleteEntry will not display the text.  Basically If I change field "Name" from code behind entry will not dispaly it. How to achive this? Thank you.

**Comment by zleao** [comment] 2023-06-22 13:41
Can you provide a sample reproducing the problem.
Thanks!

**Comment by zleao** [comment] 2023-08-23 06:45
Maybe you need to trigger the PropertyChanged of the list itself. Not sure, since I had no sample to test this behavior.
Closing this for now. Would need more information to continue...

**Closed by zleao** 2023-08-23 06:45 UTC
